---
title: "Demo Dashboard: Lebenserwartung"
author: "Johannes Feldhege"
format: 
  dashboard: 
    nav-buttons: [github]
    github: https://github.com/jfeldhege/dashboard_lifeexp
theme: [spacelab]
---

```{r}
#| label: load libraries
#| echo: false
#| warning: false
#| error: false

library(ggplot2)
library(dplyr)
library(ggalt)
library(knitr)
library(plotly)
library(DT)

```


```{r}
#| label: load data
#| echo: false
#| warning: false
#| error: false
#| message: false

quiet <- function(x) { 
  sink(tempfile()) 
  on.exit(sink()) 
  invisible(force(x)) 
} 


quiet(tuesdata <- tidytuesdayR::tt_load('2023-12-05'))

le <- tuesdata$life_expectancy
leda <- tuesdata$life_expectancy_different_ages
lefm <- tuesdata$life_expectancy_female_male

```

#  {.sidebar}

Dieses Quarto Dashboard dient zum Testen der Funktionalitäten von [Quarto Dashboards](https://quarto.org/docs/dashboards/), welche mit der Version 1.4 von Quarto eingeführt werden sollen. 

Die Daten wurden im Rahmen von [TidyTuesday](https://github.com/rfordatascience/tidytuesday/tree/master/data/2023/2023-12-05) am 05.12.2023 veröffentlicht.


# Deutschland
```{r}
#| echo: false

de_le <- le %>% 
  filter(Entity == "Germany") %>% 
  arrange(Year)

de_leda <- leda %>% 
  filter(Entity == "Germany") %>% 
  arrange(Year)

de_lefm <- lefm %>% 
  filter(Entity == "Germany") %>% 
  arrange(Year)
```



## Row

```{r}
#| content: valuebox
#| title: "Lebenserwartung in Deutschland 2021"

list(
  icon = "file-medical",
  color = "primary",
  value = round(de_le$LifeExpectancy[de_le$Year == max(de_le$Year)], 2)
)
```

```{r}
#| content: valuebox
#| title: "Differenz in Lebenserwartung Weiblich zu Männlich, 2021"

list(
  icon = "gender-female",
  color = "secondary",
  value = round(de_lefm$LifeExpectancyDiffFM[de_lefm$Year == max(de_lefm$Year)], 2)
)
```


## Row

```{r}
#| title: Lebenserwartung in Deutschland über die Zeit
ggplot(de_le, aes(x = Year, y = LifeExpectancy)) +
  geom_point() + 
  labs(x = "Jahr", y = "Lebenserwartung") +
  theme_minimal(base_size = 14)
```



```{r}
#| title: Lebenserwartung in Deutschland in unterschiedlichen Altersgruppen
de_leda %>% 
  filter(Year >= 1950) %>% 
  tidyr::pivot_longer(cols = starts_with("Life"), names_to = "Age") %>% 
  ggplot(aes(x = Year, y = value, color = Age)) +
  geom_point() +
  labs(x = "Jahr", y = "Lebenserwartung", color = "Lebenserwartung in diesem Alter") +
  theme_minimal(base_size = 14)
```


# Kontinente

```{r}
#| echo: false

co <- c("Europe", "Northern America", "Latin America and the Caribbean", 
        "Africa", "Oceania", "Asia")

co_le <- le %>% 
  filter(Entity %in% co) %>% 
  filter(Year >= 1950) %>% 
  mutate(Entity = ifelse(Entity == "Latin America and the Caribbean", "Latin America/Caribbean", Entity))
```


## Row {height=60%}

```{r}
#| title: Lebenserwartung pro Kontinent 1950 - 2021
p <- co_le %>% 
  ggplot(aes(x = Year, y = LifeExpectancy, color = Entity)) + 
  geom_point(aes(frame = Year)) +
  labs(x = "Lebenserwartung", y = "Kontinent") +
  theme_minimal()

ggplotly(p, tooltip = c("color", "x", "y")) %>%
  animation_opts(frame = 300, easing = "linear", redraw = FALSE)
```

```{r}
#| title: Veränderung der Lebenserwartung zwischen 1950 und 2021
co_le2 <- co_le %>% 
  filter(Year %in% c(1950, 2021)) %>% 
  mutate(Year = factor(Year))

ggplot(co_le2, aes(x = LifeExpectancy, y = reorder(Entity, LifeExpectancy))) +
  geom_line() +
  geom_point(aes(color = Year), size = 3) +
  theme(legend.position = "bottom") +
  labs(x = "Lebenserwartung", y = "Kontinent") +
  theme_minimal(base_size = 14)
```


## Row {height=40%}

```{r}
#| title: Lebenserwartung pro Kontinent 1950 - 2021

co_le %>% 
  mutate(LifeExpectancy = round(LifeExpectancy, 1)) %>% 
  select("Continent" = Entity, Year, "Life Expectancy" = LifeExpectancy) %>% 
  datatable(fillContainer = FALSE, options = list(pageLength = 10))
```

# Welt {orientation="columns"}

## Column {width=70%}

```{r}
#| title: Lebenserwartung 2021

country_df <- map_data("world")

le2 <- le %>% 
  filter(Year == "2021") %>% 
  mutate(Entity = case_when(
                            Entity == "Democratic Republic of Congo" ~ "Democratic Republic of the Congo",
                            Entity == "Congo" ~ "Republic of Congo",
                            Entity == "Cote d'Ivoire" ~ "Ivory Coast",
                            Entity == "East Timor" ~ "Timor-Leste",
                            .default = Entity),
         LifeExpectancy = round(LifeExpectancy, 1))


country_df <- country_df %>% 
  mutate(region = case_when(region == "USA" ~ "United States",
                            region == "UK" ~ "United Kingdom",
                            region == "Czech Republic" ~ "Czechia",
                            region == "Cote d'Ivoire" ~ "Ivory Coast",
                            region == "Trinidad" ~ "Trinidad and Tobago",
                            region == "Antigua" ~ "Antigua and Barbuda",
                            region == "Swaziland" ~ "Eswatini",
                            subregion == "Hong Kong" ~ "Hong Kong",
                            subregion == "Macao" ~ "Macao",
                            .default = region))


# join data

world <- left_join(country_df %>% rename(Country = region), 
                   le2 %>% rename(Country = Entity),
                   by = "Country")

#plot

p <- ggplot(world, aes(long, lat, group = group)) +
  
  geom_polygon(aes(label = Country, fill = LifeExpectancy),

               colour = alpha("white", 1/2), size = 0.05)  +
  
  scale_fill_viridis_c(option = "plasma") +
  
  theme_void()

ggplotly(p)
```

## Column {width=30%}

```{r}
#| title: Tabelle Lebenserwartung 2021

le2  %>% 
  arrange(desc(LifeExpectancy)) %>% 
  select(Country = Entity, "Life Expectancy" = LifeExpectancy) %>% 
  filter(Country %in% country_df$region) %>% 
  datatable(fillContainer = FALSE, options = list(pageLength = 10))
```